export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_IN_PROGRESS = "FETCH_DATA_IN_PROGRESS";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const TEST = "TEST";
export const FETCH_POSSIBLE_TYPES = "FETCH_POSSIBLE_TYPES";
export const FETCH_POSSIBLE_TYPES_SUCCESS = "FETCH_POSSIBLE_TYPES_SUCCESS";
export const REMOVE_TYPE_FROM_FILTER = "REMOVE_TYPE_FROM_FILTER";
export const ADD_TYPE_TO_FILTER = "ADD_TYPE_TO_FILTER";
